---
- name: Create the databases
  mysql_db:
    name: "{{ item.name }}"
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    state: present
    login_unix_socket: "{{ openio_galera_socket }}"
  with_items: "{{ openio_galera_databases }}"
  register: _db
  ignore_errors: "{{ ansible_check_mode }}"
  tags: configure

- name: Copy database init scripts
  copy:
    src: "{{ item.item.init_script }}"
    dest: "/tmp/{{ item.item.init_script | basename }}"
    mode: "0600"
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined
  tags: configure

- name: Initialise databases
  mysql_db:
    name: "{{ item.item.name }}"
    state: import
    target: "/tmp/{{ item.item.init_script | basename }}"
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    login_unix_socket: "{{ openio_galera_socket }}"
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined
  tags: configure

- name: Delete init scripts from the server
  file:
    name: "/tmp/{{ item.item.init_script | basename }}"
    state: absent
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined
  tags: configure

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host|default('localhost') }}"
    priv: "{{ item.priv }}"
    append_privs: "{{ item.append_privs|default('no') }}"
    login_user: root
    login_password: "{{ openio_galera_root_password }}"
    state: present
    login_unix_socket: "{{ openio_galera_socket }}"
  with_items: "{{ openio_galera_users }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: configure
...
