---
- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status == 'enabled'

- name: Install repository Epel
  package:
    name: epel-release
    state: present
  when: openio_galera_repo_epel_managed
...
